Repository Co-Studo/Co-Studo-front, pull requests merged in 2022-11, with the labels that each got.

#66 [Park] Icon Component
  .storybook/main.js
  package-lock.json
  package.json
  src/assets/icons/anonymous.svg
  src/assets/icons/bell.svg
  src/assets/icons/crown.svg
  src/assets/icons/index.tsx
  src/assets/icons/lock.svg
  src/assets/icons/star.svg
  src/components/MyStudyInfoCard/index.tsx
  src/components/common/Icon/icon.stories.tsx
  src/components/common/Icon/index.tsx
  src/components/common/Text/index.tsx
  src/custom.d.ts
  src/styled.d.ts
  src/styles/theme.ts
  webpack/webpack.common.js
Labels: ✨ Feature

#68 [Park] FlexBox Component
  src/components/common/FlexBox/flexBox.stories.tsx
  src/components/common/FlexBox/index.tsx
Labels: ✨ Feature

#70 [Dony] fix slider validation bug.
  src/components/common/Slider/Slider.tsx
  src/components/common/Slider/slider.stories.tsx
  src/utils/validation.ts
Labels: 🐛 Bug

#76 [Dony] Text 컴포넌트에 ellipsis 속성 추가
  src/components/common/Text/index.tsx
  src/components/common/Text/text.stories.tsx
  src/styles/fonts.ts
Labels: ✨ Feature

#79 [Hemdi] Form, TextField 컴포넌트 개선 및 추가 구현
  src/components/common/Form/Form.tsx
  src/components/common/Form/TextField.tsx
  src/components/common/Form/form.stories.tsx
  src/components/common/Form/form.styled.tsx
  src/components/common/Form/index.tsx
  src/components/common/Form/useForm.tsx
  src/components/common/TextField/index.tsx
  src/components/common/TextField/textField.stories.tsx
  src/components/common/TextField/textField.styled.tsx
  src/components/common/TextField/useTextValidation.tsx
Labels: ✨ Feature, ♻️ Refactoring

#88 [Dony] Icon 사이즈 통일
  src/assets/icons/anonymous.svg
  src/assets/icons/bell.svg
  src/assets/icons/crown.svg
  src/assets/icons/index.tsx
  src/assets/icons/lock.svg
  src/assets/icons/star.svg
  src/components/common/Icon/index.tsx
Labels: ♻️ Refactoring

#92 [Hemdi] FlexBoxSX 사이즈, 간격 관련 속성 추가
  src/components/common/FlexBox/index.tsx
  src/components/common/FlexBox/spacing.tsx
Labels: ✨ Feature
